### ISSUE TITLE
Find out the reason behind internal server error on contract verification

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockscout#4]

**Comment by schmir-at-bb** [comment]
Here's a verified contract: http://blockexplorer.trustlines.foundation/address/0x215c6b7ed48564e0ee2f1c8ed9a31388e7a74ec1/contracts

The problem was that `SECRET_KEY_BASE` was not set. Verification may take a long time, I assume because it downloads the parity executable. We may have to increase the timeouts in nginx.

**Comment by berndbohmeier** [comment]
Just  for my knowledge, did you find documentation or something about that?

**Comment by schmir-at-bb** [comment]
I don't remember completely. I was aware of the mix task to generate the secret. I guess it had been in the documentation back when I looked at it when I first installed it.
